# Generated by Django 3.1.3 on 2021-04-15 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Inductee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('surname', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=64, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='Телефон')),
                ('birthday', models.DateField(null=True, verbose_name='Дата рождения')),
                ('military_category', models.CharField(choices=[('Не определена', 'Не определена'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('Б1', 'Б1'), ('Б2', 'Б2'), ('Б3', 'Б3'), ('Б4', 'Б4'), ('В', 'В'), ('Г', 'Г'), ('Д', 'Д')], default='Не определена', max_length=14, verbose_name='Категория годности')),
                ('military_status', models.CharField(choices=[('Поставлен на учёт', 'Поставлен на учёт'), ('Военнослужащий', 'Военнослужащий'), ('В запасе', 'В запасе'), ('Снят с учёта', 'Снят с учёта')], default='Поставлен на учёт', max_length=20, verbose_name='Военный статус')),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.city', verbose_name='Город')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Призывник',
                'verbose_name_plural': 'Призывники',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=64, verbose_name='Заголовок уведомления')),
                ('text', models.TextField(max_length=2000, verbose_name='Текст уведомления')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата уведомления')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.CreateModel(
            name='Recruiting_office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Военкомат',
                'verbose_name_plural': 'Военкоматы',
            },
        ),
        migrations.CreateModel(
            name='Subpoena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_to_come', models.DateTimeField(verbose_name='Когда')),
                ('for_what', models.TextField(max_length=2000, verbose_name='Причина вызова')),
                ('to_whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.inductee', verbose_name='Кому')),
                ('where_to_come', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recruiting_office', verbose_name='Куда')),
            ],
            options={
                'verbose_name': 'Повестка',
                'verbose_name_plural': 'Повестки',
            },
        ),
        migrations.CreateModel(
            name='Responsible_person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('surname', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=64, verbose_name='Отчество')),
                ('post', models.CharField(max_length=64, verbose_name='Должность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответственное лицо',
                'verbose_name_plural': 'Ответственные лица',
            },
        ),
        migrations.CreateModel(
            name='Military_ID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_issued', models.DateTimeField(verbose_name='Когда выдан')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recruiting_office', verbose_name='Кем выдан')),
                ('to_whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.inductee', verbose_name='Кому выдан')),
            ],
            options={
                'verbose_name': 'Военный билет',
                'verbose_name_plural': 'Военные билеты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=64, verbose_name='Заголовок сообщения')),
                ('text', models.TextField(max_length=2000, verbose_name='Текст сообщения')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата сообщения')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Обработано')),
                ('addresser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.inductee', verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Answer_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(max_length=2000, verbose_name='Текст ответа')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.message', verbose_name='Сообщение')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.responsible_person', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
